export const recipeData = {
  id: "recipe-123",
  title: "Perplexity + Claude로 경쟁사 분석 보고서 30분 완성 후기",
  author: {
    nickname: "soowan",
    avatarUrl: "", 
  },
  createdAt: "5일 전",
  views: "2,103",
  likes: 24,
  toolsFlow: ["ChatGPT", "Vrew", "Canva AI", "ElevenLabs"],
  // 3번 요청: 프롬프트 창을 4개로 확장
  steps: [
    {
      stepNumber: 1,
      toolName: "ChatGPT",
      category: "기획 및 스크립트",
      description: "30초 숏폼 스크립트 작성",
      prompt: `"30초 숏폼용 스크립트 작성해줘. 주제는 [주제]"`,
    },
    {
      stepNumber: 2,
      toolName: "Vrew",
      category: "영상 편집",
      description: "스크립트 기반 영상 컷 편집 및 자막 자동 생성",
      prompt: `(Vrew 프로그램 내 텍스트 입력 기능 활용)`,
    },
    {
      stepNumber: 3,
      toolName: "Canva AI",
      category: "이미지 소스 생성",
      description: "썸네일 디자인 자동 생성",
      prompt: `"유튜브 썸네일 만들어줘. 텍스트: [제목], 톤: 밝고 강렬하게"`,
    },
    {
      stepNumber: 4,
      toolName: "ElevenLabs",
      category: "음성 생성",
      description: "스크립트를 자연스러운 한국어 남성 목소리로 변환",
      prompt: `[ChatGPT가 작성한 스크립트 내용 붙여넣기]`,
    },
  ],
  commentsCount: 29,
  comments: [
    {
      id: 1,
      author: "AI마스터",
      avatarLetter: "A",
      timeAgo: "1시간 전",
      content: "정말 유용한 공유 감사해요! Notion 연동 부분이 특히 도움됐어요.",
      likes: 14,
      isAuthor: false,
    },
    {
      id: 2,
      author: "생산성덕후",
      avatarLetter: "생",
      timeAgo: "50분 전",
      content: "Notion 데이터베이스 속성 구조도 공유해주실 수 있나요?",
      likes: 9,
      isAuthor: false,
    },
    {
      id: 3,
      author: "작성자",
      avatarLetter: "S",
      timeAgo: "35분 전",
      content: "@생산성덕후 다음 포스트에 Notion 템플릿 링크랑 같이 올릴게요!",
      likes: 6,
      isAuthor: true,
    },
  ],
};